export const members = [
  {name: 'Flip Lord', shortname: 'come', wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Doofenschmirtz', shortname: 'squi',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Nut Busters', shortname: 'vinn',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: '24 Karat Gold', shortname: 'jimm',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Skibbideeznuts', shortname: 'ecof',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Team Canada', shortname: 'gale',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Streets 1:12', shortname: 'pots',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Slightly Stoopid', shortname: 'maht',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Ball Spikers', shortname: 'devv',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
  {name: 'Little Giants', shortname: 'plac',  wins: 0, KO: 0, M1G: 0, M1PS: 0, M1PF: 0, M2G: 0, M2PS: 0, M2PF: 0, CHPI: 0, CHG: 0, CHPS: 0, CHPF: 0},
]// kickoffLAN(7), major1[groupstage(8), POSemi(8), POFinals(3)], major2[groupstage(8), POSemi(8), POFinals(3)], championship[PISemi(10), Groups(12), POSemi(8), POFinals(3)]

export let Regional1Matchups = ['vinn', 'squi', 'jimm', 'come', 'gale', 'ecof', 'maht', 'pots', 'devv', 'plac']
export let KickoffMatchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Regional2Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Regional3Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Major1Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Regional4Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Regional5Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Regional6Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let Major2Matchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']
export let ChampionshipMatchups = ['TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', 'plac']

export let Regional1 = {
  'come' : ['Daniel', 'Beastmode', 'Kv1', 'Chronic', 'Catalysm'],
  'squi' : ['Trk511', 'M0nkey m00n', 'Motta', 'Atomik', 'Tawk'],
  'vinn' : ['Firstkiller', 'Lostt', 'Lj', 'Jknaps', '2die4'],
  'jimm' : ['Dralii', 'Atow', 'Rise', 'Exotiik', 'Justin'],
  'ecof' : ['Nwpo', 'Yanxnz', 'Apparentlyjack', 'Bananahead', 'Oski'],
  'gale' : ['Kiileerrz', 'Vatira', 'Kofyr', 'Nass', 'Sphinx'],
  'pots' : ['Zen', 'Atomic', 'Drufinho', 'Fever', 'Torsos'],
  'maht' : ['Rw9', 'Stizzy', 'Joyo', 'Joreuz', 'Seikoo'],
  'devv' : ['Archie', 'Diaz', 'Reveal', 'Swiftt', 'Crr'],
  'plac' : ['Majicbear', 'Oaly', 'Cheese'],
}
export let Regional2 = {
  'come' : [Regional1['come'][0], Regional1['come'][1], Regional1['come'][2], Regional1['come'][3], 'Tehqoz'],
  'squi' : [Regional1['squi'][0], Regional1['squi'][1], Regional1['squi'][2], Regional1['squi'][3], Regional1['squi'][4]],
  'vinn' : [Regional1['vinn'][0], Regional1['vinn'][1], Regional1['vinn'][2], 'Chausette45', Regional1['vinn'][4]],
  'jimm' : [Regional1['jimm'][0], Regional1['jimm'][1], Regional1['jimm'][2], Regional1['jimm'][3], Regional1['jimm'][4]],
  'ecof' : [Regional1['ecof'][0], Regional1['ecof'][1], Regional1['ecof'][2], Regional1['ecof'][3], Regional1['ecof'][4]],
  'gale' : [Regional1['gale'][0], Regional1['gale'][1], Regional1['gale'][2], Regional1['gale'][3], Regional1['gale'][4]],
  'pots' : [Regional1['pots'][0], Regional1['pots'][1], Regional1['pots'][2], Regional1['pots'][3], Regional1['pots'][4]],
  'maht' : [Regional1['maht'][0], Regional1['maht'][1], Regional1['maht'][2], Regional1['maht'][3], Regional1['maht'][4]],
  'devv' : [Regional1['devv'][0], Regional1['devv'][1], Regional1['devv'][2], Regional1['devv'][3], Regional1['devv'][4]],
  'plac' : [Regional1['plac'][0], Regional1['plac'][1], Regional1['plac'][2], Regional1['plac'][3], Regional1['plac'][4]],
}
export let Regional3 = {
  'come' : [Regional2['come'][0], Regional2['come'][1], Regional2['come'][2], Regional2['come'][3], Regional2['come'][4]],
  'squi' : [Regional2['squi'][0], Regional2['squi'][1], Regional2['squi'][2], Regional2['squi'][3], Regional2['squi'][4]],
  'vinn' : [Regional2['vinn'][0], Regional2['vinn'][1], Regional2['vinn'][2], Regional2['vinn'][3], Regional2['vinn'][4]],
  'jimm' : [Regional2['jimm'][0], Regional2['jimm'][1], Regional2['jimm'][2], Regional2['jimm'][3], Regional2['jimm'][4]],
  'ecof' : [Regional2['ecof'][0], Regional2['ecof'][1], Regional2['ecof'][2], Regional2['ecof'][3], Regional2['ecof'][4]],
  'gale' : [Regional2['gale'][0], Regional2['gale'][1], Regional2['gale'][2], Regional2['gale'][3], Regional2['gale'][4]],
  'pots' : [Regional2['pots'][0], Regional2['pots'][1], Regional2['pots'][2], Regional2['pots'][3], Regional2['pots'][4]],
  'maht' : [Regional2['maht'][0], Regional2['maht'][1], Regional2['maht'][2], Regional2['maht'][3], Regional2['maht'][4]],
  'devv' : [Regional2['devv'][0], Regional2['devv'][1], Regional2['devv'][2], Regional2['devv'][3], Regional2['devv'][4]],
  'plac' : [Regional2['plac'][0], Regional2['plac'][1], Regional2['plac'][2], Regional2['plac'][3], Regional2['plac'][4]],
}
export let Regional4 = {
  'come' : [Regional3['come'][0], Regional3['come'][1], Regional3['come'][2], Regional3['come'][3], Regional3['come'][4]],
  'squi' : [Regional3['squi'][0], Regional3['squi'][1], Regional3['squi'][2], Regional3['squi'][3], Regional3['squi'][4]],
  'vinn' : [Regional3['vinn'][0], Regional3['vinn'][1], Regional3['vinn'][2], Regional3['vinn'][3], Regional3['vinn'][4]],
  'jimm' : [Regional3['jimm'][0], Regional3['jimm'][1], Regional3['jimm'][2], Regional3['jimm'][3], Regional3['jimm'][4]],
  'ecof' : [Regional3['ecof'][0], Regional3['ecof'][1], Regional3['ecof'][2], Regional3['ecof'][3], Regional3['ecof'][4]],
  'gale' : [Regional3['gale'][0], Regional3['gale'][1], Regional3['gale'][2], Regional3['gale'][3], Regional3['gale'][4]],
  'pots' : [Regional3['pots'][0], Regional3['pots'][1], Regional3['pots'][2], Regional3['pots'][3], Regional3['pots'][4]],
  'maht' : [Regional3['maht'][0], Regional3['maht'][1], Regional3['maht'][2], Regional3['maht'][3], Regional3['maht'][4]],
  'devv' : [Regional3['devv'][0], Regional3['devv'][1], Regional3['devv'][2], Regional3['devv'][3], Regional3['devv'][4]],
  'plac' : [Regional3['plac'][0], Regional3['plac'][1], Regional3['plac'][2], Regional3['plac'][3], Regional3['plac'][4]],
}
export let Regional5 = {
  'come' : [Regional4['come'][0], Regional4['come'][1], Regional4['come'][2], Regional4['come'][3], Regional4['come'][4]],
  'squi' : [Regional4['squi'][0], Regional4['squi'][1], Regional4['squi'][2], Regional4['squi'][3], Regional4['squi'][4]],
  'vinn' : [Regional4['vinn'][0], Regional4['vinn'][1], Regional4['vinn'][2], Regional4['vinn'][3], Regional4['vinn'][4]],
  'jimm' : [Regional4['jimm'][0], Regional4['jimm'][1], Regional4['jimm'][2], Regional4['jimm'][3], Regional4['jimm'][4]],
  'ecof' : [Regional4['ecof'][0], Regional4['ecof'][1], Regional4['ecof'][2], Regional4['ecof'][3], Regional4['ecof'][4]],
  'gale' : [Regional4['gale'][0], Regional4['gale'][1], Regional4['gale'][2], Regional4['gale'][3], Regional4['gale'][4]],
  'pots' : [Regional4['pots'][0], Regional4['pots'][1], Regional4['pots'][2], Regional4['pots'][3], Regional4['pots'][4]],
  'maht' : [Regional4['maht'][0], Regional4['maht'][1], Regional4['maht'][2], Regional4['maht'][3], Regional4['maht'][4]],
  'devv' : [Regional4['devv'][0], Regional4['devv'][1], Regional4['devv'][2], Regional4['devv'][3], Regional4['devv'][4]],
  'plac' : [Regional4['plac'][0], Regional4['plac'][1], Regional4['plac'][2], Regional4['plac'][3], Regional4['plac'][4]],
}
export let Regional6 = {
  'come' : [Regional5['come'][0], Regional5['come'][1], Regional5['come'][2], Regional5['come'][3], Regional5['come'][4]],
  'squi' : [Regional5['squi'][0], Regional5['squi'][1], Regional5['squi'][2], Regional5['squi'][3], Regional5['squi'][4]],
  'vinn' : [Regional5['vinn'][0], Regional5['vinn'][1], Regional5['vinn'][2], Regional5['vinn'][3], Regional5['vinn'][4]],
  'jimm' : [Regional5['jimm'][0], Regional5['jimm'][1], Regional5['jimm'][2], Regional5['jimm'][3], Regional5['jimm'][4]],
  'ecof' : [Regional5['ecof'][0], Regional5['ecof'][1], Regional5['ecof'][2], Regional5['ecof'][3], Regional5['ecof'][4]],
  'gale' : [Regional5['gale'][0], Regional5['gale'][1], Regional5['gale'][2], Regional5['gale'][3], Regional5['gale'][4]],
  'pots' : [Regional5['pots'][0], Regional5['pots'][1], Regional5['pots'][2], Regional5['pots'][3], Regional5['pots'][4]],
  'maht' : [Regional5['maht'][0], Regional5['maht'][1], Regional5['maht'][2], Regional5['maht'][3], Regional5['maht'][4]],
  'devv' : [Regional5['devv'][0], Regional5['devv'][1], Regional5['devv'][2], Regional5['devv'][3], Regional5['devv'][4]],
  'plac' : [Regional5['plac'][0], Regional5['plac'][1], Regional5['plac'][2], Regional5['plac'][3], Regional5['plac'][4]],
}
export let prizes = {
  'come' : [0, 0, 0],
  'squi' : [0, 0, 0],
  'vinn' : [0, 0, 0],
  'jimm' : [0, 0, 0],
  'ecof' : [0, 0, 0],
  'gale' : [0, 0, 0],
  'pots' : [0, 0, 0],
  'maht' : [0, 0, 0],
  'devv' : [0, 0, 0],
  'plac' : [0, 0, 0],
}

export let players = [
{player: 'Trk511', team: 'Twisted Minds', role: ''},
{player: 'Kiileerrz', team: 'Team Falcons', role: ''},
{player: 'Rw9', team: 'Team Falcons', role: ''},
{player: 'Nwpo', team: 'Twisted Minds', role: ''},
{player: 'Daniel', team: 'NRG', role: ''},
{player: 'Beastmode', team: 'NRG', role: ''},
{player: 'Dralii', team: 'Team Falcons', role: ''},
{player: 'Firstkiller', team: 'Shopify Rebellion', role: ''},
{player: 'Atomic', team: 'NRG', role: ''},
{player: 'Zen', team: 'Team Vitality', role: ''},
{player: 'Atomik', team: 'Magnifico', role: ''},
{player: 'Atow', team: 'Karmine Corp', role: ''},
{player: 'Yanxnz', team: 'Furia Esports', role: ''},
{player: 'Lostt', team: 'Furia Esports', role: ''},
{player: 'Vatira', team: 'Karmine Corp', role: ''},
{player: 'Rise', team: 'GenG Mobil1 Racing', role: ''},
{player: 'Lj', team: 'Shopify Rebellion', role: ''},
{player: 'Chronic', team: 'Spacestation Gaming', role: ''},
{player: 'Drufinho', team: 'Team Secret', role: ''},
{player: 'Stizzy', team: 'Team Vitality', role: ''},
{player: 'Kv1', team: 'Team Secret', role: ''},
{player: 'Apparentlyjack', team: 'Geekay Esports', role: ''},
{player: 'Joreuz', team: 'Ninjas in Pyjamas', role: ''},
{player: 'Motta', team: 'Team Secret', role: ''},
{player: 'Cheese', team: 'FUT Esports', role: ''},
{player: 'Bananahead', team: 'Wildcard', role: ''},
{player: 'Vksailen', team: 'F/A', role: ''},
{player: 'Leoro', team: 'FUT Esports', role: 'inactive'},
{player: 'M0nkey m00n', team: 'Twisted Minds', role: ''},
{player: 'Fever', team: 'Wildcard', role: ''},
{player: 'Torres8232', team: 'Looking for organization', role: ''},
{player: 'Archie', team: 'Gentle Mates Alpine', role: ''},
{player: 'Majicbear', team: 'GenG Mobil1 Racing', role: ''},
{player: 'Exotiik', team: 'Team Vitality', role: ''},
{player: 'Superlachie', team: 'PWR', role: ''},
{player: 'T7lm', team: 'The Vicious', role: ''},
{player: 'Reveal', team: 'Spacestation Gaming', role: ''},
{player: 'Oaly', team: 'Ninjas in Pyjamas', role: ''},
{player: 'Joyo', team: 'Geekay Esports', role: ''},
{player: 'Swiftt', team: 'Furia Esports', role: ''},
{player: 'Kofyr', team: 'Shopify Rebellion', role: ''},
{player: 'Torsos', team: 'Wildcard', role: ''},
{player: 'Rezears', team: 'Magnifico', role: ''},
{player: 'Fiberr', team: 'PWR', role: ''},
{player: 'Rez', team: 'F/A', role: ''},
{player: 'Kaka', team: 'TSM', role: ''},
{player: 'Amphis', team: 'TSM', role: ''},
{player: 'Catalysm', team: 'Project Delacruz', role: ''},
{player: 'M7sn', team: 'Team Vision', role: ''},
{player: 'Oski', team: 'Gentle Mates Alpine', role: ''},
{player: 'Tox', team: 'Magnifico', role: ''},
{player: 'Lunr', team: 'Lunr-Kekkles-Laxin', role: ''},
{player: 'Justin', team: 'GenG Mobil1 Racing', role: ''},
{player: 'Sweaty', team: 'Pioneers', role: ''},
{player: 'Sosa', team: 'FUT Esports', role: ''},
{player: '2die4', team: 'Pioneers', role: ''},
{player: 'Caleb', team: 'F/A', role: ''},
{player: 'Sphinx', team: 'Project Delacruz', role: ''},
{player: 'Suspect', team: 'The Vicious', role: ''},
{player: 'Scrub', team: 'Im fine in the west', role: ''},
{player: 'Diaz', team: 'Spacestation Gaming', role: ''},
{player: 'Snowyy', team: 'Five Fears', role: ''},
{player: 'Crr', team: 'Ninjas in Pyjamas', role: ''},
{player: 'Drknown', team: 'DTN', role: ''},
{player: 'Yujin', team: 'Gentlebench', role: ''},
{player: 'Gus', team: 'PWR', role: ''},
{player: 'Abdullah', team: 'ROC Esports', role: ''},
{player: 'Reysbull', team: 'MIBR', role: ''},
{player: 'Ivan', team: 'F/A', role: ''},
{player: 'Nass', team: 'Gentle Mates Alpine', role: ''},
{player: 'Juicy', team: 'Karmine Corp', role: ''},
{player: 'Laxin', team: 'Lunr-Kekkles-Laxin', role: ''},
{player: 'Caard', team: 'Sunset', role: ''},
{player: 'Seikoo', team: 'Geekay Esports', role: ''},
{player: 'Retals', team: '', role: 'retired'},
{player: 'Frosty', team: 'FUT Esports', role: ''},
{player: 'Carca', team: 'F/A', role: ''},
{player: 'Twiz', team: 'ROC Esports', role: ''},
{player: 'Scrzbbles', team: '', role: 'retired'},
{player: 'M7md', team: 'NRD Esports', role: ''},
{player: 'Revezy', team: 'Drku-Revezy', role: ''},
{player: 'Hntr', team: 'F/A', role: ''},
{player: 'Wisty', team: 'Amethyst', role: ''},
{player: 'Sadness', team: 'F/A', role: ''},
{player: 'Crn', team: 'Amethyst', role: ''},
{player: 'Bemmz', team: 'Chromax', role: ''},
{player: 'Nxghtt', team: 'Amethyst', role: ''},
{player: 'Insp1re', team: 'Le Bosh', role: ''},
{player: 'Ghaazi', team: 'ROC Esports', role: ''},
{player: 'Ballerrees', team: 'Northstar Gaming', role: ''},
{player: 'Accro', team: 'Man City Esports', role: ''},
{player: 'Rizon', team: 'F/A', role: ''},
{player: 'Droppz', team: 'Chromax', role: ''},
{player: 'Hockser', team: 'F/A', role: ''},
{player: 'Rehzzy', team: 'Hogan Mode', role: ''},
{player: 'Itachi', team: '', role: 'retired'},
{player: 'Lct', team: 'Northstar Gaming', role: ''},
{player: 'Kam', team: 'F/A', role: ''},
{player: 'Luiisp', team: 'Pioneers', role: ''},
{player: 'Oscillon', team: 'F/A', role: ''},
{player: 'Aztr', team: 'F/A', role: ''},
{player: 'B2sel', team: 'The Vicious', role: 'sub'},
{player: 'Chicago', team: 'G2 Esports', role: ''},
{player: 'Toxiic', team: 'Sonics', role: ''},
{player: 'Tho', team: 'Tho-Dead-Chanel', role: ''},
{player: 'Andy', team: '1', role: ''},
{player: 'Suco', team: 'Amethyst', role: ''},
{player: '2piece', team: 'Redacted', role: ''},
{player: 'Wahvey', team: 'Redacted', role: ''},
{player: 'Trook', team: 'DTN', role: ''},
{player: 'Sqqp', team: 'F/A', role: ''},
{player: 'Arju', team: 'Shuffles Kittens', role: ''},
{player: 'Yazeed', team: 'F/A', role: ''},
{player: 'O0vvl', team: 'F/A', role: ''},
{player: 'Realize', team: 'F/A', role: ''},
{player: 'Speed', team: 'Shuffles Kittens', role: ''},
{player: 'Relatingwave', team: 'Shuffles Kittens', role: ''},
{player: 'Davi', team: 'F/A', role: ''},
{player: 'Royales', team: '1', role: ''},
{player: 'Smw', team: 'Team Vision', role: ''},
{player: 'Venom', team: 'The Vicious', role: ''},
{player: 'Fsol', team: 'F/A', role: ''},
{player: 'Yand', team: '', role: 'retired'},
{player: 'Maxeew', team: 'Kinotrope Gaming', role: ''},
{player: 'Big gez', team: 'F/A', role: ''},
{player: 'Paarth', team: 'Top Leh', role: ''},
{player: 'Eekso', team: 'Geekay Esports', role: 'coach'},
{player: 'Aris', team: 'M80', role: ''},
{player: 'Fades', team: 'Tsurani', role: ''},
{player: 'Creedeny', team: 'F/A', role: ''},
{player: 'Gyro', team: 'Unreal Nightmare', role: ''},
{player: 'Nadr', team: 'F/A', role: ''},
{player: 'Kns', team: 'Novadrift', role: ''},
{player: 'Hawk', team: 'SKRIMZWORLD', role: ''},
{player: 'Zineel', team: '1', role: ''},
{player: 'Crispy', team: '100X35 Esports', role: ''},
{player: 'Twister', team: '77Blocks', role: ''},
{player: 'Furlashh', team: 'Kinotrope Gaming', role: ''},
{player: 'Prompt', team: 'F/A', role: ''},
{player: 'Twnzr', team: '77Blocks', role: ''},
{player: 'Brad', team: 'Chromax', role: ''},
{player: 'Dansku', team: 'Salami', role: ''},
{player: 'Regser', team: '354 Esports', role: ''},
{player: 'Growlii', team: 'Hogan Mode', role: ''},
{player: 'Cobbo', team: 'SKRIMZWORLD', role: ''},
{player: 'Ziyad', team: 'F16 Esports', role: ''},
{player: 'Caiotg1', team: 'Sunset', role: ''},
{player: 'Mittaen', team: 'F/A', role: ''},
{player: 'Percy', team: 'Ciel', role: ''},
{player: 'Ovampierz', team: 'OFF', role: ''},
{player: 'Klaus queridinho', team: 'F/A', role: ''},
{player: 'Lunatic', team: 'Daybreak Frontline', role: ''},
{player: 'Nai', team: 'Ground Zero Gaming', role: ''},
{player: 'Lynx', team: 'F16 Esports', role: ''},
{player: 'Dayys', team: 'F/A', role: ''},
{player: 'Leodkn', team: 'F/A', role: ''},
{player: 'Fiv3up', team: 'Dignitas', role: ''},
{player: 'Radosin', team: 'Gentlebench', role: ''},
{player: 'Nico', team: 'Novo Esports', role: ''},
{player: 'Badnezz', team: 'Sick!', role: ''},
{player: 'Alpe', team: 'F/A', role: ''},
{player: 'Acronik', team: 'Novo Esports', role: ''},
{player: 'Pingu', team: 'F/A', role: ''},
{player: 'Mat', team: 'Compact-Rysfox-Mat', role: ''},
{player: 'Tehqoz', team: 'Five Fears', role: ''},
{player: 'Hocke', team: 'hey bro', role: ''},
{player: 'Giuk', team: 'Novo Esports', role: ''},
{player: 'Ianpinheiro', team: 'Overlooked', role: ''},
{player: 'Lionblaze', team: 'Schnitzelhaus', role: ''},
{player: 'Youngstar', team: 'F/A', role: ''},
{player: 'Kevin', team: 'Project Delacruz', role: ''},
{player: 'Weins', team: 'Zen Esports', role: ''},
{player: 'Risk', team: 'Ground Zero Gaming', role: ''},
{player: 'Dapz', team: 'Synthesis', role: ''},
{player: 'Kaydop', team: 'The Last Dance', role: ''},
{player: 'Blue', team: 'F/A', role: ''},
{player: 'Hxll0', team: 'F/A', role: ''},
{player: 'Vops1', team: 'F/A', role: ''},
{player: 'Nush', team: 'DTN', role: ''},
{player: 'Rysfox', team: 'Compact-Rysfox-Mat', role: ''},
{player: 'Jimmo', team: 'F/A', role: ''},
{player: 'Mira', team: 'F/A', role: ''},
{player: 'Kekkles', team: 'Lunr-Kekkles-Laxin', role: ''},
{player: 'Ajg', team: 'Synergy', role: ''},
{player: 'Burn', team: 'Dreamstation', role: ''},
{player: 'Tjester', team: 'F/A', role: ''},
{player: 'K', team: 'F/A', role: ''},
{player: 'Dorito', team: 'Synergy', role: ''},
{player: 'Mohanned', team: 'Zen Esports', role: ''},
{player: 'Pan', team: 'F/A', role: ''},
{player: 'Mikeboy', team: 'Sonics', role: ''},
{player: 'Misery', team: 'Novadrift', role: 'sub'},
{player: 'Kexii', team: 'F/A', role: ''},
{player: 'Pagsi', team: 'Tsurani', role: ''},
{player: 'Dappluto', team: 'Overlooked', role: ''},
{player: 'Syke', team: 'F/A', role: ''},
{player: 'Ejby', team: 'Man City Esports', role: ''},
{player: 'Creamz', team: 'Top Leh', role: ''},
{player: 'Finn', team: 'Tsurani', role: ''},
{player: 'Qtipz', team: 'F/A', role: ''},
{player: 'Tossis', team: 'Sailing Esports', role: ''},
{player: 'Sek', team: 'F/A', role: ''},
{player: 'Davitrox', team: 'ShindeN', role: ''},
{player: 'Dvku', team: 'F/A', role: ''},
{player: 'Cabdllah', team: 'OFF', role: 'sub'},
{player: 'Yukeo', team: 'AKA HERO', role: ''},
{player: 'Wiiilooo', team: 'F/A', role: ''},
{player: 'Hatem', team: 'OFF', role: ''},
{player: 'Brenox', team: 'Eighty6 Esports', role: ''},
{player: 'Madssssss', team: 'F/A', role: ''},
{player: 'Renshiro', team: 'ROUNDS', role: ''},
{player: 'Aztral', team: 'Gameward', role: ''},
{player: 'Zenulous', team: 'Zenulous-Vult-Euxsy', role: ''},
{player: 'Gunz', team: 'Five Fears', role: ''},
{player: 'Glowz', team: 'F/A', role: ''},
{player: 'Smokez', team: 'Sonics', role: ''},
{player: 'Rexo', team: 'F/A', role: ''},
{player: 'Lagly', team: 'Papo de Visao', role: ''},
{player: 'Breezi', team: 'F/A', role: ''},
{player: 'Skillsteal', team: 'Astronic Esports', role: ''},
{player: 'Friction', team: 'Unity', role: ''},
{player: 'Nym', team: 'F/A', role: ''},
{player: 'Umbroken', team: 'Overlooked', role: ''},
{player: 'M6r', team: 'F/A', role: ''},
{player: 'Rust ez95', team: 'Gameward', role: ''},
{player: 'Rxii', team: 'Hogan Mode', role: ''},
{player: 'Rooster', team: 'F/A', role: ''},
{player: 'Hazo', team: 'Feastaboniam', role: ''},
{player: 'Baconhero', team: 'F/A', role: ''},
{player: 'Creamyy', team: 'F/A', role: ''},
{player: 'Night', team: 'Ciel', role: ''},
{player: 'Tawk', team: 'Redacted', role: ''},
{player: 'Devour', team: 'Astronic Esports', role: ''},
{player: 'Porsas', team: 'Xing Xi Xooters', role: 'sub'},
{player: 'Ultimatehntr97', team: 'F/A', role: ''},
{player: 'Bal', team: 'F/A', role: ''},
{player: 'Stake', team: 'CosmiCo Esports', role: ''},
{player: 'Simas', team: '100X35 Esports', role: ''},
{player: 'Vfbi', team: 'OFF', role: ''},
{player: 'Squigly', team: 'Uhuh', role: ''},
{player: 'Lxucha', team: 'F/A', role: ''},
{player: 'Kash', team: 'Kinotrope Gaming', role: ''},
{player: 'Ahduhm', team: 'Feastaboniam', role: ''},
{player: 'Sozya1', team: 'F/A', role: ''},
{player: 'Jushu', team: 'F/A', role: ''},
{player: 'Nasty', team: 'F/A', role: ''},
{player: 'Abood', team: 'Infamous', role: ''},
{player: 'Aziz', team: 'Brainstorm Esports', role: 'coach'},
{player: 'Skworchi', team: 'F/A', role: ''},
{player: 'Energizer', team: 'F/A', role: ''},
{player: 'Juck', team: 'F/A', role: ''},
{player: 'Eliakimza', team: 'Looking for organization', role: ''},
{player: 'Matt', team: 'F/A', role: ''},
{player: 'Pzy', team: '100X35 Esports', role: ''},
{player: 'Fnsi', team: 'Rapier', role: ''},
{player: 'Dvo', team: 'M80', role: ''},
{player: 'Compact', team: 'Compact-Rysfox-Mat', role: ''},
{player: 'Pndh', team: 'Ciel', role: ''},
{player: 'Zany', team: 'Team HSK', role: ''},
{player: 'Bad', team: 'F/A', role: ''},
{player: 'Paraapelka', team: 'F/A', role: ''},
{player: 'Jazii', team: 'Low Block', role: ''},
{player: 'Xprt', team: 'Lotus 8 Esports', role: ''},
{player: 'Lunar', team: 'Northstar Gaming', role: ''},
{player: 'Snipjz', team: 'Oblivion Esports', role: ''},
{player: 'Aqua', team: 'Dignitas', role: ''},
{player: 'Isl6nii', team: 'F/A', role: ''},
{player: 'Shugs', team: 'F/A', role: ''},
{player: 'Abdulaziz', team: 'Infamous', role: ''},
{player: 'Justuszzz', team: 'F/A', role: ''},
{player: 'Mtzr', team: 'Gentlebench', role: ''},
{player: 'Echo', team: 'F/A', role: ''},
{player: 'Neiko', team: 'Str1ve eSports', role: ''},
{player: 'Gawfs', team: 'Low Block', role: ''},
{player: 'Ramzy', team: 'Omen Esports', role: ''},
{player: 'Rixy', team: 'Omen Esports', role: ''},
{player: 'Euxsy', team: 'Zenulous-Vult-Euxsy', role: ''},
{player: 'Inspire', team: 'F/A', role: ''},
{player: 'Nemr', team: 'F/A', role: ''},
{player: 'Mohammed', team: 'F/A', role: ''},
{player: 'Tatagane', team: 'F/A', role: ''},
{player: 'Bunney', team: 'F/A', role: ''},
{player: 'Strutic', team: 'Death Cloud Esports', role: ''},
{player: 'Aguz', team: 'FOFOS', role: ''},
{player: 'Rmn', team: 'ShindeN', role: ''},
{player: 'Evoh', team: 'Dignitas', role: ''},
{player: 'Sour', team: 'F/A', role: ''},
{player: 'Mysterious', team: 'F/A', role: ''},
{player: 'Tonio', team: 'F/A', role: ''},
{player: 'Noahsaki', team: 'LAntique Esport', role: ''},
{player: 'Majid', team: 'F/A', role: ''},
{player: 'Vulty', team: 'F/A', role: ''},
{player: 'Ewp', team: 'F/A', role: ''},
{player: 'Taroco', team: 'F/A', role: ''},
{player: 'Chikage', team: 'Infamous', role: ''},
{player: 'Zombiefreak', team: 'F/A', role: ''},
{player: 'Tempoh', team: 'Man City Esports', role: ''},
{player: 'Viitin', team: 'F/A', role: ''},
{player: 'Arafar', team: 'Str1ve eSports', role: ''},
{player: 'Kroado', team: 'F/A', role: ''},
{player: 'Jknaps', team: 'G2 Esports', role: ''},
{player: 'Rayagoat', team: 'F/A', role: ''},
{player: 'Abscrazy', team: 'Big Dawgs', role: ''},
{player: 'Roods', team: 'MAMÍFEROS', role: ''},
{player: 'Zeeyad', team: 'zzzz', role: ''},
{player: 'Garrettg', team: 'G.A.S.', role: ''},
{player: 'Sultan', team: 'Team Phoenix', role: ''},
{player: 'Druee', team: 'Unreal Nightmare', role: ''},
{player: 'Kuipier', team: 'F/A', role: ''},
{player: 'Jg', team: 'MAMÍFEROS', role: ''},
{player: 'Jsm', team: 'F/A', role: ''},
{player: 'Staar', team: 'F/A', role: ''},
{player: 'Starwindss', team: 'Blazar Academy', role: ''},
{player: 'Jeff', team: 'CosmiCo Esports', role: ''},
{player: 'Israkan', team: 'F/A', role: ''},
{player: 'Shadi', team: 'F/A', role: ''},
{player: 'Chub', team: 'Maccas Drive Thru', role: ''},
{player: 'Nachosky', team: 'F/A', role: ''},
{player: 'Cx9', team: 'F/A', role: ''},
{player: 'Kaizen', team: 'Xing Xi Xooters', role: ''},
{player: 'Willie', team: 'Flare Esport', role: ''},
{player: 'Extra', team: 'Karmine Corp', role: 'coach'},
{player: 'Tcorrell', team: 'F/A', role: ''},
{player: 'Kevinacho', team: 'Novadrift', role: ''},
{player: 'Nawaf', team: 'We Dont Know', role: ''},
{player: 'Plgabriel', team: 'True Neutral Academy Black', role: ''},
{player: 'Morse', team: 'F/A', role: ''},
{player: 'Valid', team: 'Ground Zero Gaming', role: ''},
{player: 'Jb0x', team: 'Daybreak Frontline', role: ''},
{player: 'Matthew', team: 'Maccas Drive Thru', role: ''},
{player: 'Ayyjayy', team: 'G.A.S.', role: ''},
{player: 'T9berh', team: 'F/A', role: ''},
{player: 'Z4', team: 'We Dont Know', role: ''},
{player: 'Sum', team: 'F/A', role: ''},
{player: 'Xyro', team: 'F/A', role: ''},
{player: 'Bairechuu', team: 'F/A', role: ''},
{player: 'Werty', team: 'Looking for organization', role: ''},
{player: 'Mass', team: 'Omen Esports', role: 'sub'},
{player: 'Sobral', team: 'Oblivion Esports', role: ''},
{player: 'Khiernan', team: 'F/A', role: ''},
{player: 'Hughesy', team: 'Team Zorn', role: ''},
{player: 'Mech', team: 'M80', role: ''},
{player: 'Lba', team: 'F/A', role: ''},
{player: 'N', team: 'F/A', role: ''},
{player: 'N1tr', team: 'F/A', role: ''},
{player: 'Comm', team: 'Top Leh', role: ''},
{player: 'Jori', team: 'F/A', role: ''},
{player: 'Zalo', team: 'F/A', role: ''},
{player: 'Twistt', team: 'Eighty6 Esports', role: ''},
{player: 'Sergeant', team: 'F/A', role: ''},
{player: 'Tkay', team: 'F/A', role: ''},
{player: 'Ntri', team: 'F/A', role: ''},
{player: 'Declan', team: 'Synthesis', role: ''},
{player: 'Kal', team: 'F/A', role: ''},
{player: 'Frenchie', team: 'Team Zorn', role: ''},
{player: 'Machi', team: 'Sailing Esports', role: ''},
{player: 'Ams', team: 'Espada', role: ''},
{player: 'Anyeelo', team: 'Team HSK', role: ''},
{player: 'Hisoka', team: 'Twisted Minds', role: 'sub'},
{player: 'Apples', team: 'F/A', role: ''},
{player: 'Nerve', team: 'F/A', role: ''},
{player: 'Nmj', team: 'F/A', role: ''},
{player: 'Toastie', team: 'F/A', role: ''},
{player: 'Ben', team: 'The Pups', role: ''},
{player: 'Kito', team: 'F/A', role: ''},
{player: 'Pj', team: 'F/A', role: ''},
{player: 'Snoozy', team: 'F/A', role: ''},
{player: 'Wylew', team: 'F/A', role: ''},
{player: 'Misty', team: 'Uhuh', role: ''},
{player: 'Baz', team: 'F/A', role: ''},
{player: 'BunnyDummy', team: 'Uhuh', role: ''},
{player: 'Life', team: 'Unreal Nightmare', role: 'rookie'},
{player: 'Mu3', team: 'F/A', role: ''},
{player: 'Pr', team: 'F/A', role: ''},
{player: 'Bebbangboy', team: 'F/A', role: ''},
{player: 'Zett', team: 'LeaveNoWitness', role: ''},
{player: 'Rellec', team: 'The Pups', role: ''},
{player: 'Keta', team: 'F/A', role: ''},
{player: 'Villain arc', team: 'F/A', role: ''},
{player: 'Lazybear', team: 'Str1ve eSports', role: ''},
{player: 'Creepy', team: 'Espada', role: ''},
{player: 'Kisai', team: 'F/A', role: ''},
{player: 'Sscary', team: 'F/A', role: ''},
{player: 'Mozzarella', team: 'Gameward', role: 'rookie'},
{player: 'Ren', team: 'Pulse Clan WCB', role: ''},
{player: 'Nym0', team: 'zzzz', role: ''},
{player: 'Marky', team: 'F/A', role: ''},
{player: 'Rigorous', team: 'F/A', role: ''},
{player: 'Jovan', team: 'F/A', role: ''},
{player: 'Oevoh', team: 'F/A', role: ''},
{player: 'Darklight', team: 'F/A', role: ''},
{player: 'Halden', team: 'F/A', role: ''},
{player: 'Nook', team: 'F/A', role: ''},
{player: 'Shark', team: 'F/A', role: ''},
{player: 'Tristiano swartznaldo', team: 'F/A', role: ''},
{player: 'Fiasco', team: 'F/A', role: ''},
{player: 'Firefoxd', team: 'LUK Esports', role: ''},
{player: 'Hyderr', team: 'GHT', role: ''},
{player: 'Worstplejer', team: 'F/A', role: ''},
{player: 'Xeelfine', team: 'F/A', role: ''},
{player: 'Reis zoo', team: 'F/A', role: ''},
{player: 'Aloneeyy', team: 'F/A', role: ''},
{player: 'Gramma', team: 'GHT', role: ''},
{player: 'Mala7', team: 'Austrian Force', role: ''},
{player: 'Bihxn', team: 'F/A', role: ''},
{player: 'Kylo', team: 'Xing Xi Xooters', role: ''},
{player: 'Mu', team: 'Team Phoenix', role: ''},
{player: 'Dead', team: 'Tho-Dead-Chanel', role: ''},
{player: 'Ell1srai', team: 'F/A', role: ''},
{player: 'Forece', team: 'WOO', role: ''},
{player: 'Hireo', team: 'F/A', role: ''},
{player: 'Chippy', team: 'Chippy Chips', role: ''},
{player: 'Bazlenks', team: 'F/A', role: ''},
{player: 'Popo', team: 'F/A', role: ''},
{player: 'Oath', team: 'CMK', role: ''},
{player: 'Mav', team: 'F/A', role: ''},
{player: 'Repeat', team: 'CMK', role: ''},
{player: 'Maykinhoo', team: 'F/A', role: ''},
{player: 'Trin', team: 'F/A', role: ''},
{player: 'Teschow', team: 'F/A', role: ''},
{player: 'Velocity', team: 'Drones', role: ''},
{player: 'Galaxy', team: 'White Rabbit Gaming', role: ''},
{player: 'Ezgles', team: 'F/A', role: ''},
{player: 'Jelly', team: 'F/A', role: ''},
{player: 'Tank', team: 'UHUH', role: ''},
{player: 'Ritsune', team: 'zzzz', role: 'sub'},
{player: 'Ghassan', team: 'F/A', role: ''},
{player: 'Aboturki', team: 'F/A', role: ''},
{player: 'Ix', team: 'F/A', role: ''},
{player: 'Muss', team: 'F/A', role: ''},
{player: 'Hexic', team: 'F/A', role: ''},
{player: 'V3ziz', team: 'INVADERS BLUES', role: ''},
{player: 'Arrow', team: 'Fernstella', role: ''},
{player: 'Prodz', team: 'F/A', role: ''},
{player: 'Fktor', team: 'F/A', role: ''},
{player: 'Profile', team: 'F/A', role: ''},
{player: 'Bananacat', team: 'White Rabbit Gaming', role: ''},
{player: 'Arth', team: 'F/A', role: ''},
{player: 'Seck', team: 'los maroleiros', role: ''},
{player: 'Uncle bill', team: 'F/A', role: ''},
{player: 'Arch', team: 'Yokohama F. Marinos Esports', role: ''},
{player: 'Lasa', team: 'Chippy Chips', role: ''},
{player: 'Bora', team: 'F/A', role: ''},
{player: 'Kuro', team: 'F/A', role: ''},
{player: 'Swazz', team: 'CMK', role: ''},
{player: 'Beasty', team: 'Sick!', role: ''},
{player: 'Davoof', team: 'F/A', role: ''},
{player: 'Amatel', team: 'Fernstella', role: ''},
{player: 'Jweyts', team: 'NXT', role: ''},
{player: 'Hadiryas', team: 'YURRRR', role: ''},
{player: 'Rizzo', team: 'G2 Esports', role: ''},
{player: 'Stolen', team: '1', role: 'coach'},
{player: 'Turbopolsa', team: '', role: 'retired'},
{player: 'Tide', team: '100X35 Esports', role: ''},
{player: 'N0ah', team: 'Man City Esports', role: 'coach'},
{player: 'Ops', team: 'Al Qadsiah', role: ''},
{player: 'Yua', team: 'Al Qadsiah', role: 'sub'},
{player: 'Michi', team: 'Amethyst', role: 'coach'},
{player: 'C0mplex', team: 'Astronic Esports', role: 'coach'},
{player: 'Onizumaa', team: 'Astronic Esports', role: ''},
{player: 'DiazNA', team: 'Big Work', role: ''},
{player: 'Blaze', team: 'BlazeBeefCoconut', role: ''},
{player: 'Chief beef', team: 'BlazeBeefCoconut', role: ''},
{player: 'Nemoto', team: 'Blue Torch', role: 'coach'},
{player: 'Shaolon', team: 'Blue Torch', role: 'sub'},
{player: 'Shaolon', team: 'Blue Torch', role: 'sub'},
{player: 'Kaoshi', team: 'Chromax', role: 'coach'},
{player: 'Charlieb', team: 'Dangerous Esports Club', role: ''},
{player: 'Saizen', team: 'Dangerous Esports Club', role: ''},
{player: 'Vadyy', team: 'Dangerous Esports Club', role: ''},
{player: 'Roll dizz', team: 'Deleted Gaming', role: 'coach'},
{player: 'Drku', team: 'Drku-Revezy', role: ''},
{player: 'Ahmad', team: 'F/A', role: 'coach'},
{player: 'Armonik', team: 'F/A', role: ''},
{player: 'Asn_rubiix', team: 'F/A', role: ''},
{player: 'Azapatos', team: 'F/A', role: ''},
{player: 'Dark', team: 'F/A', role: ''},
{player: 'Happymeal', team: 'F/A', role: ''},
{player: 'Marc_by_8', team: 'F/A', role: ''},
{player: 'Mikan', team: 'F/A', role: ''},
{player: 'Nick', team: 'M80', role: 'coach'},
{player: 'Okhalid', team: 'F/A', role: ''},
{player: 'Virtuoso', team: 'F/A', role: ''},
{player: 'Farz', team: 'FOFOS', role: 'coach'},
{player: 'Arsenal', team: 'Fortnite Flick', role: 'retired'},
{player: 'Flitz', team: 'M80', role: 'sub'},
{player: 'Jamaicancoconut', team: 'Fortnite Flick', role: ''},
{player: 'Brunovisqui', team: 'Furia Esports', role: 'coach'},
{player: 'Snaz', team: 'FUT Esports', role: 'sub'},
{player: 'Squishymuffinz', team: 'G.A.S.', role: ''},
{player: 'Alternix', team: 'Gaming Up', role: 'coach'},
{player: 'Kevpert', team: 'GenG Mobil1 Racing', role: 'coach'},
{player: 'Rawgreg', team: 'GenG Mobil1 Racing', role: 'coach'},
{player: 'Snaski', team: 'Gentle Mates Alpine', role: 'coach'},
{player: 'Slayer', team: 'Godfidence', role: 'coach'},
{player: 'Emmy', team: 'Ground Zero Gaming', role: ''},
{player: 'Jimi', team: 'Ground Zero Gaming', role: 'coach'},
{player: 'Pinkjelly', team: 'Ground Zero Gaming', role: ''},
{player: 'Queenmorgie', team: 'Ground Zero Gaming', role: ''},
{player: 'Aztromick', team: 'MIBR', role: ''},
{player: 'Pekitas', team: 'MIBR', role: 'coach'},
{player: 'Sad', team: 'MIBR', role: ''},
{player: 'Trill', team: 'Project Delacruz', role: 'coach'},
{player: 'Zez0nix', team: 'ROC Esports', role: 'coach'},
{player: 'Violentpanda', team: 'Shopify Rebellion', role: 'coach'},
{player: 'Shuffleverse', team: 'Shuffles Kittens', role: 'coach'},
{player: 'Xpére', team: 'Spacestation Gaming', role: 'coach'},
{player: 'Chausette45', team: 'The Last Dance', role: 'retired'},
{player: 'Fairy peak!', team: 'The Last Dance', role: 'retired'},
{player: 'Kérian', team: 'TSK', role: ''},
{player: 'Rizex', team: 'Synergy', role: ''},
{player: 'Greenwarrior', team: 'Synthesis', role: 'coach'},
{player: 'D7oom-24', team: 'Team Falcons', role: 'coach'},
{player: 'Stl', team: 'Team Secret', role: 'coach'},
{player: 'Davinsano', team: 'F/A', role: ''},
{player: 'Azfura', team: 'Team Twitter', role: ''},
{player: 'Fishhr', team: 'Dignitas', role: 'coach'},
{player: 'Spoodah', team: 'Team Twitter', role: ''},
{player: 'Bo0odi44', team: 'Team Vision', role: 'coach'},
{player: 'Meshal', team: 'Team Vision', role: 'sub'},
{player: 'Mesho', team: 'Team Vision', role: ''},
{player: 'Alpha54', team: 'Team Vitality', role: 'inactive'},
{player: 'Eversax', team: 'Team Vitality', role: 'coach'},
{player: 'Ostyn', team: 'The Boys', role: 'coach'},
{player: 'Trey', team: 'The Boys', role: 'coach'},
{player: 'Imaginaxion', team: 'The Vicious', role: 'coach'},
{player: 'Pluvo', team: 'Tokyo Tigers', role: ''},
{player: 'Gear', team: 'TRUSH me', role: ''},
{player: 'Kamiikahzii', team: 'TRUSH me', role: ''},
{player: 'Skillz', team: 'TRUSH me', role: ''},
{player: 'Negative', team: 'Tsurani', role: 'sub'},
{player: 'Sad junior', team: 'Twisted Minds', role: 'coach'},
{player: 'Senzo', team: 'Twisted Minds', role: 'coach'},
{player: 'Noly', team: 'Lotus 8 Esports', role: ''},
{player: 'Appelsous', team: 'White Rabbit Gaming', role: 'sub'},
{player: 'Wee_casper', team: 'White Rabbit Gaming', role: ''},
{player: 'Jimmah', team: 'Wildcard', role: 'coach'},
{player: 'Tynobad', team: 'Yokohama F. Marinos Esports', role: 'coach'},
{player: 'Vult', team: 'Zenulous-Vult-Euxsy', role: ''},

]
export let teams = [
{team: 'Team Falcons', region: 'MENA'},
{team: 'Twisted Minds', region: 'MENA'},
{team: 'Karmine Corp', region: 'EU'},
{team: 'NRG', region: 'NA'},
{team: 'G2 Esports', region: 'NA'},
{team: 'The Ultimates', region: 'NA'},
{team: 'Furia Esports', region: 'SAM'},
{team: 'Team Vitality', region: 'EU'},
{team: 'FUT Esports', region: 'NA'},
{team: 'Wildcard', region: 'OCE'},
{team: 'Team Secret', region: 'SAM'},
{team: 'Dignitas', region: 'EU'},
{team: 'GenG Mobil1 Racing', region: 'NA'},
{team: 'Geekay Esports', region: 'EU'},
{team: 'Spacestation Gaming', region: 'NA'},
{team: 'TSM', region: 'OCE'},
{team: '9Lives', region: 'NA'},
{team: 'Helfie Chiefs', region: 'OCE'},
{team: 'Virtuspro', region: 'APAC'},
{team: 'SKRIMZWORLD', region: 'OCE'},
{team: 'PWR', region: 'OCE'},
{team: 'Limitless', region: 'SSA'},
{team: 'Shopify Rebellion', region: 'NA'},
{team: 'Al Qadsiah', region: 'MENA'},
{team: 'hey (with rizz)', region: 'SSA'},
{team: 'Complexity Gaming', region: 'NA'},
{team: 'Ninjas in Pyjamas', region: 'EU'},
{team: 'Team Reds', region: 'MENA'},
{team: 'Corinthians Esports', region: 'SAM'},
{team: 'Gentle Mates Alpine', region: 'EU'},
{team: 'Godfidence', region: 'SAM'},
{team: 'Le bosh', region: 'SSA'},
{team: 'Elevate', region: 'APAC'},
{team: 'Sleeping', region: 'MENA'},
{team: '100%', region: 'NA'},
{team: 'Kinotrope Gaming', region: 'APAC'},
{team: 'Deleted Gaming', region: 'NA'},
{team: 'Team Evo', region: 'NA'},
{team: 'Moonrise', region: 'SAM'},
{team: 'Strictly Business', region: 'NA'},
{team: '77blocks', region: 'SSA'},
{team: 'Dekubopdumnem', region: 'APAC'},
{team: 'Caliente', region: 'EU'},
{team: 'Synergy', region: 'MENA'},
{team: 'God speed', region: 'APAC'},
{team: 'Pirates on a Boat', region: 'NA'},
{team: 'F4WD', region: 'EU'},
{team: 'Big Dawgs', region: 'APAC'},
{team: 'Blue Torch', region: 'APAC'},
{team: 'Fire Force', region: 'APAC'},
{team: 'Paifhers', region: 'APAC'},
{team: 'Pineapple Cake', region: 'APAC'},
{team: 'Praise', region: 'APAC'},
{team: 'Project Delacruz', region: 'APAC'},
{team: 'RandomLine', region: 'APAC'},
{team: 'Red Torch', region: 'APAC'},
{team: 'Revenue Redeemers', region: 'APAC'},
{team: 'Rounds', region: 'APAC'},
{team: 'Team Phoenix', region: 'APAC'},
{team: 'The Backseat Lovers', region: 'APAC'},
{team: 'Uhuh', region: 'APAC'},
{team: 'Yokohama F Marinos Esports', region: 'APAC'},
{team: 'YURRRR', region: 'APAC'},
{team: 'Zen Esports', region: 'APAC'},
{team: 'Man City Esports', region: 'EU'},
{team: '354 Esports', region: 'EU'},
{team: '5M Esports', region: 'EU'},
{team: 'AKA HERO', region: 'EU'},
{team: 'Antique Esport', region: 'EU'},
{team: 'Austrian Force', region: 'EU'},
{team: 'Chippy Chips', region: 'EU'},
{team: 'Dangerous Esports Club', region: 'EU'},
{team: 'FlyBack eSports', region: 'EU'},
{team: 'German Hermanos', region: 'EU'},
{team: 'GODSENT', region: 'EU'},
{team: 'Heracles Esports', region: 'EU'},
{team: 'Hogan Mode', region: 'EU'},
{team: 'LAntique Esport', region: 'EU'},
{team: 'Low Block', region: 'EU'},
{team: 'Musk', region: 'EU'},
{team: 'Novo Esports', region: 'EU'},
{team: 'NXT', region: 'EU'},
{team: 'PimpMyRide', region: 'EU'},
{team: 'Pioneers', region: 'EU'},
{team: 'Pirots 3', region: 'EU'},
{team: 'Quick Esports', region: 'EU'},
{team: 'Red Devils', region: 'EU'},
{team: 'Redemption', region: 'EU'},
{team: 'RQS Esports', region: 'EU'},
{team: 'Salami', region: 'EU'},
{team: 'Sick!', region: 'EU'},
{team: 'Stick mick', region: 'EU'},
{team: 'Str1ve eSports', region: 'EU'},
{team: 'Super Team', region: 'EU'},
{team: 'Team Ascend', region: 'EU'},
{team: 'Team BDS', region: 'EU'},
{team: 'TwentyStars', region: 'EU'},
{team: 'Welcome To Earth', region: 'EU'},
{team: '305', region: 'MENA'},
{team: '777', region: 'MENA'},
{team: '305', region: 'MENA'},
{team: '777', region: 'MENA'},
{team: 'EKW', region: 'MENA'},
{team: 'Espada', region: 'MENA'},
{team: 'F16 Esports', region: 'MENA'},
{team: 'Flare Esport', region: 'MENA'},
{team: 'Infamous', region: 'MENA'},
{team: 'INVADERS BLUES', region: 'MENA'},
{team: 'Joga Bonito', region: 'MENA'},
{team: 'NOname', region: 'MENA'},
{team: 'NRD Esports', region: 'MENA'},
{team: 'OFF', region: 'MENA'},
{team: 'ORYX Esports', region: 'MENA'},
{team: 'ROC Esports', region: 'MENA'},
{team: 'Team Vision', region: 'MENA'},
{team: 'The Vicious', region: 'MENA'},
{team: 'We Dont Know', region: 'MENA'},
{team: 'zzzz', region: 'MENA'},
{team: '1', region: 'NA'},
{team: '445', region: 'NA'},
{team: '100X35 Esports', region: 'NA'},
{team: '12 Bricks', region: 'NA'},
{team: '445', region: 'NA'},
{team: '72PC', region: 'NA'},
{team: 'belly bean boys', region: 'NA'},
{team: 'ben', region: 'NA'},
{team: 'Birth', region: 'NA'},
{team: 'BlazeBeefCoconut', region: 'NA'},
{team: 'Bomb Squad', region: 'NA'},
{team: 'Bronze Baddies', region: 'NA'},
{team: 'Carl', region: 'NA'},
{team: 'CMK', region: 'NA'},
{team: 'Cold', region: 'NA'},
{team: 'Collegiate Demons', region: 'NA'},
{team: 'CRL Retirement Home', region: 'NA'},
{team: 'Ctrl Alt Defeat', region: 'NA'},
{team: 'Doodle Bangers', region: 'NA'},
{team: 'Empty Space', region: 'NA'},
{team: 'Fellas', region: 'NA'},
{team: 'Flashes of Brilliance', region: 'NA'},
{team: 'Fortnite Flick', region: 'NA'},
{team: 'GAS', region: 'NA'},
{team: 'GenG Mobil1 Racing Black', region: 'NA'},
{team: 'Gentlemen', region: 'NA'},
{team: 'Golden Hour Esports', region: 'NA'},
{team: 'Gribble My Balls', region: 'NA'},
{team: 'Happy Burritos', region: 'NA'},
{team: 'Hey bro', region: 'NA'},
{team: 'iz im dreamin', region: 'NA'},
{team: 'Juiced', region: 'NA'},
{team: 'La Familia', region: 'NA'},
{team: 'LaQuímica e-Sports', region: 'NA'},
{team: 'Le Sserafim', region: 'NA'},
{team: 'Levitate Esports Club', region: 'NA'},
{team: 'Lil Step Bros', region: 'NA'},
{team: 'LLama Champions', region: 'NA'},
{team: 'Lotus 8 Esports', region: 'NA'},
{team: 'Luminosity Gaming', region: 'NA'},
{team: 'M80', region: 'NA'},
{team: 'Mexaclica', region: 'NA'},
{team: 'Mission Rank A', region: 'NA'},
{team: 'MrFearlite', region: 'NA'},
{team: 'nah', region: 'NA'},
{team: 'Netherlamericanada', region: 'NA'},
{team: 'no idea', region: 'NA'},
{team: 'norms', region: 'NA'},
{team: 'Noxem', region: 'NA'},
{team: 'Ohio Club', region: 'NA'},
{team: 'pepegashake', region: 'NA'},
{team: 'Polar Knights', region: 'NA'},
{team: 'PreJump', region: 'NA'},
{team: 'Psycho Rangers', region: 'NA'},
{team: 'Pulse Clan WCB', region: 'NA'},
{team: 'Qup Mana', region: 'NA'},
{team: 'Revelation', region: 'NA'},
{team: 'Sapphire', region: 'NA'},
{team: 'Schnitzelhaus', region: 'NA'},
{team: 'Seas And Peas', region: 'NA'},
{team: 'Sharlitt Feenix', region: 'NA'},
{team: 'shmoo', region: 'NA'},
{team: 'Shuffles Kittens', region: 'NA'},
{team: 'Southeast Shooters', region: 'NA'},
{team: 'Stromboli', region: 'NA'},
{team: 'sup', region: 'NA'},
{team: 'Team EXE', region: 'NA'},
{team: 'Team Twitter', region: 'NA'},
{team: 'Team Whoppa', region: 'NA'},
{team: 'The Boys', region: 'NA'},
{team: 'The Final Order', region: 'NA'},
{team: 'The Maryland nibbling narwhals', region: 'NA'},
{team: 'The Swim Team', region: 'NA'},
{team: 'Three Blind Mice', region: 'NA'},
{team: 'TRUSH me', region: 'NA'},
{team: 'Valkyrie Array', region: 'NA'},
{team: 'Virtual Esports', region: 'NA'},
{team: 'Wandering Lobsters', region: 'NA'},
{team: 'WOO', region: 'NA'},
{team: 'xT', region: 'NA'},
{team: 'YapVille', region: 'NA'},
{team: 'Zookeepers', region: 'NA'},
{team: 'Big Chungus', region: 'OCE'},
{team: 'Brainstorm Esports', region: 'OCE'},
{team: 'Ground Zero Gaming', region: 'OCE'},
{team: 'Im fine in the west', region: 'OCE'},
{team: 'Leles', region: 'OCE'},
{team: 'LOUDer', region: 'OCE'},
{team: 'Maccas Drive Thru', region: 'OCE'},
{team: 'No Hat No Play', region: 'OCE'},
{team: 'RTT', region: 'OCE'},
{team: 'Reborn Titans', region: 'OCE'},
{team: 'Rumpus Room Wizards', region: 'OCE'},
{team: 'Team Zorn', region: 'OCE'},
{team: 'The Pups', region: 'OCE'},
{team: 'Tsurani', region: 'OCE'},
{team: 'We Suck', region: 'OCE'},
{team: 'Zawoo', region: 'OCE'},
{team: 'Amethyst', region: 'SAM'},
{team: 'Amigos do Baait', region: 'SAM'},
{team: 'Blazar Academy', region: 'SAM'},
{team: 'Chromax', region: 'SAM'},
{team: 'Eighty6 Esports', region: 'SAM'},
{team: 'Endless', region: 'SAM'},
{team: 'Erased', region: 'SAM'},
{team: 'Flexibility', region: 'SAM'},
{team: 'FOFOS', region: 'SAM'},
{team: 'Gaming Up', region: 'SAM'},
{team: 'LeaveNoWitness', region: 'SAM'},
{team: 'los maroleiros', region: 'SAM'},
{team: 'LUK Esports', region: 'SAM'},
{team: 'MAMÍFEROS', region: 'SAM'},
{team: 'MIBR', region: 'SAM'},
{team: 'Nakamas', region: 'SAM'},
{team: 'Oblivion Esports', region: 'SAM'},
{team: 'Overlooked', region: 'SAM'},
{team: 'Papo de Visao', region: 'SAM'},
{team: 'Rocos Gaming', region: 'SAM'},
{team: 'ShindeN', region: 'SAM'},
{team: 'Sunset', region: 'SAM'},
{team: 'Team Silenced', region: 'NA'},
{team: 'True Neutral Academy Black', region: 'SAM'},
{team: 'Wifu', region: 'SAM'},
{team: 'Ziollis Forbidden Sons', region: 'SAM'},
{team: 'Astronic Esports ', region: 'SSA'},
{team: 'Aureon eSports', region: 'SSA'},
{team: 'Bird', region: 'SSA'},
{team: 'BTF Esports', region: 'SSA'},
{team: 'CosmiCo Esports', region: 'SSA'},
{team: 'Death Cloud Esports', region: 'SSA'},
{team: 'GeneSix', region: 'SSA'},
{team: 'Haibo', region: 'SSA'},
{team: 'ICE Esports', region: 'SSA'},
{team: 'Looking for organization', region: 'SSA'},
{team: 'Omen Esports', region: 'SSA'},
{team: 'Omnius Gaming', region: 'SSA'},
{team: 'Team Floeppa', region: 'SSA'},
{team: 'The Punishers', region: 'SSA'},
{team: 'Unity', region: 'SSA'},
{team: 'White Rabbit Gaming', region: 'SSA'},
{team: 'Super-Fiberr-Gus', region: 'OCE'},
{team: 'Lunr-Kekkles-Laxin', region: 'OCE'},
{team: 'Five Fears', region: 'SSA'},
{team: 'DTN', region: 'MENA'},
{team: 'Drku-Revezy', region: 'EU'},
{team: 'Tho-Dead-Chanel', region: 'EU'},
{team: 'Top Leh', region: 'NA'},
{team: 'Novadrift', region: 'SAM'},
{team: 'Synthesis', region: 'SSA'},
{team: 'Dreamstation', region: 'APAC'},
{team: 'Daybreak Frontline', region: 'APAC'},
{team: 'Compact-Rysfox-Mat', region: 'EU'},
{team: 'Gameward', region: 'EU'},
{team: 'Zenulous-Vult-Euxsy', region: 'OCE'},
{team: 'Astronic Esports', region: 'SSA'},
{team: 'Tokyo Tigers', region: 'APAC'},
{team: 'Team HSK', region: 'SSA'},
{team: 'Wassup', region: 'NA'},
{team: 'Wooka Esport', region: 'EU'},
{team: 'Big Work', region: 'NA'},
{team: 'Dreifach-Reset', region: 'EU'},
{team: 'Resonal-Lev-Pigeon', region: 'NA'},
{team: 'Selaco', region: 'EU'},
{team: 'Magnifico', region: 'EU'},
{team: 'GHT', region: 'EU'},
{team: 'Pina Low Driven', region: 'EU'},
{team: 'Gentlebench', region: 'EU'},
{team: 'TKS', region: 'EU'},
{team: 'Sonics', region: 'EU'},
{team: 'Unreal Nightmare', region: 'NA'},
{team: 'Redacted', region: 'NA'},
{team: 'Ciel', region: 'NA'},
{team: 'Feastaboniam', region: 'NA'},
{team: 'Fernstella', region: 'APAC'},
{team: 'Sailing Esports', region: 'APAC'},
{team: 'Northstar Gaming', region: 'APAC'},
{team: 'Uhuh', region: 'APAC'},
{team: 'Rapier', region: 'APAC'},
{team: 'Xing Xi Xooters', region: 'APAC'},
{team: 'The Last Dance', region: 'EU'},
{team: 'HHM', region: 'APAC'},
{team: 'Sailing Esports', region: 'APAC'},
{team: 'Instant', region: 'APAC'},
{team: 'Lamb Munchers', region: 'APAC'},
{team: 'Bajak Laut Digital', region: 'APAC'},
{team: 'Cloud Esports', region: 'EU'},
{team: '100', region: 'MENA'},
{team: '4Ever', region: 'OCE'},
{team: 'Aelix', region: 'SAM'},
{team: 'Almost Nuts', region: 'OCE'},
{team: 'Awawa', region: 'MENA'},
{team: 'bandoleiros', region: 'SAM'},
{team: 'Canterbury Bulldogs', region: 'OCE'},
{team: 'Changuitos FC', region: 'SAM'},
{team: 'dont disturb us', region: 'MENA'},
{team: 'Dumb Luck Esports', region: 'OCE'},
{team: 'Emerald', region: 'SAM'},
{team: 'Enosis eSports', region: 'SAM'},
{team: 'Fear Of God', region: 'SAM'},
{team: 'Fearless', region: 'MENA'},
{team: 'Five Fears', region: 'SSA'},
{team: 'Incindies', region: 'MENA'},
{team: 'KekDubz', region: 'OCE'},
{team: 'Lethal Esports', region: 'OCE'},
{team: 'Miami Metro', region: 'OCE'},
{team: 'MMA', region: 'MENA'},
{team: 'Nkandla Style', region: 'SSA'},
{team: 'NoPlanB', region: 'SAM'},
{team: 'Nothing', region: 'MENA'},
{team: 'NoTime', region: 'SAM'},
{team: 'Ox Gaming', region: 'SSA'},
{team: 'petrol money', region: 'OCE'},
{team: 'Project S', region: 'MENA'},
{team: 'Rural', region: 'MENA'},
{team: 'Sanificados', region: 'SAM'},
{team: 'spanish pap en wors', region: 'SSA'},
{team: 'Spliced', region: 'OCE'},
{team: 'SWC', region: 'MENA'},
{team: 'Take Flyte', region: 'OCE'},
{team: 'Team Freez', region: 'OCE'},
{team: 'Team10', region: 'SSA'},
{team: 'The First', region: 'MENA'},
{team: 'Three Point Shooters', region: 'SAM'},
{team: 'Vade Esports', region: 'OCE'},
{team: 'you not a champ', region: 'OCE'},
{team: 'R.T.T.', region: 'OCE'},
{team: 'G.A.S.', region: 'NA'},
]
